---
abstract: 'provide the most appropriate HTTP client with a Future API'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  CGI: '0'
  Carp: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  FindBin: '0'
  Getopt::Long: '0'
  HTTP::Daemon: '0'
  Test::More: '0'
  URI::URL: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Future-HTTP
no_index:
  directory:
    - t
    - inc
requires:
  Filter::signatures: '0.03'
  Future: '0.31'
  HTTP::Tiny: '0'
  Moo: '2'
  perl: '5.006'
resources:
  repository: git://github.com/Corion/future-http.git
version: '0.06'
